import { ChevronLeft, FileText, Download, Heart, Activity, TrendingUp } from 'lucide-react';
import { useAppStore } from '../store/useAppStore';
 
interface TestHistoryScreenProps {
  onBack: () => void;
}
 
export function TestHistoryScreen({ onBack }: TestHistoryScreenProps) {
  const appointments = useAppStore((state) => state.appointments);
  const health = useAppStore((state) => state.health);
 
  const testHistory = appointments.filter((a) => a.status === 'completed');
 
  const totalTests = testHistory.length;
 
  const avgBpm = health.avgHR;
 
  const normalCount = testHistory.filter(
    (t) => t.result === 'Normal'
  ).length;
  const normalPercent = totalTests > 0
    ? Math.round((normalCount / totalTests) * 100)
    : 0;
 
  const getResultColor = (result?: string) => {
    switch ((result ?? '').toLowerCase()) {
      case 'normal':   return 'bg-green-100 text-green-700';
      case 'abnormal': return 'bg-red-100 text-red-700';
      default:         return 'bg-yellow-100 text-yellow-700';
    }
  };
 
  const handleDownload = (testType: string, date: string) => {
    const content = `CardioSport Medical Report\n\nTest: ${testType}\nDate: ${date}\nStatus: Normal\n\nThis report has been generated by CardioSport for demonstration purposes.`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `CardioSport_Report_${testType.replace(/\s/g, '_')}_${date.replace(/,?\s/g, '_')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };
 
  return (
    <div className="min-h-screen bg-gray-50 relative overflow-hidden">
 
      {/* Header */}
      <div className="bg-white border-b border-gray-200">
        <div className="px-6 pt-12 pb-4">
          <button
            onClick={onBack}
            className="flex items-center text-red-500 mb-4 active:opacity-50 transition-opacity"
          >
            <ChevronLeft className="w-6 h-6 mr-1" />
            <span>Back</span>
          </button>
          <h1 className="text-gray-900">Test History</h1>
        </div>
      </div>
 
      {/* Content */}
      <div className="px-6 py-6">
 
        {/* Summary Card */}
        <div className="bg-gradient-to-br from-red-500 to-pink-600 rounded-3xl p-6 mb-6 text-white">
          <h2 className="text-white mb-4">Health Summary</h2>
          <div className="grid grid-cols-3 gap-4">
            <div>
              <p className="text-3xl mb-1">{totalTests}</p>
              <p className="text-red-100 text-sm">Total Tests</p>
            </div>
            <div>
              <p className="text-3xl mb-1">{avgBpm}</p>
              <p className="text-red-100 text-sm">Avg BPM</p>
            </div>
            <div>
              <p className="text-3xl mb-1">{normalPercent}%</p>
              <p className="text-red-100 text-sm">Normal</p>
            </div>
          </div>
        </div>
 
        {/* Test History List */}
        {testHistory.length > 0 ? (
          <div className="space-y-4">
            {testHistory.map((test) => (
              <div key={test.id} className="bg-white rounded-3xl p-4 shadow-sm">
                <div className="flex items-start justify-between mb-3">
                  <div className="flex items-start">
                    <div className="w-12 h-12 bg-red-100 rounded-xl flex items-center justify-center mr-3">
                      <Heart className="w-6 h-6 text-red-600" />
                    </div>
                    <div>
                      <h3 className="text-gray-900 mb-1">{test.type}</h3>
                      <p className="text-sm text-gray-500">{test.date}</p>
                    </div>
                  </div>
                  <span className={`px-3 py-1 rounded-full text-sm ${getResultColor(test.result)}`}>
                    {test.result ?? 'Pending'}
                  </span>
                </div>
 
                <div className="bg-gray-50 rounded-2xl p-4 mb-3">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <div className="flex items-center text-sm text-gray-500 mb-1">
                        <Activity className="w-4 h-4 mr-1" />
                        Heart Rate
                      </div>
                      <p className="text-gray-900">{test.heartRate ?? 'N/A'}</p>
                    </div>
                    <div>
                      <div className="flex items-center text-sm text-gray-500 mb-1">
                        <TrendingUp className="w-4 h-4 mr-1" />
                        Status
                      </div>
                      <p className="text-gray-900">{test.result ?? 'Pending'}</p>
                    </div>
                  </div>
                  {test.doctor && (
                    <div className="mt-3 pt-3 border-t border-gray-200">
                      <p className="text-sm text-gray-500">Reviewed by {test.doctor}</p>
                    </div>
                  )}
                </div>
 
                <div className="flex gap-3">
                  <button className="flex-1 py-2.5 bg-gray-50 text-gray-900 rounded-xl active:bg-gray-100 transition-colors flex items-center justify-center">
                    <FileText className="w-4 h-4 mr-2" />
                    View Report
                  </button>
                  <button
                    onClick={() => handleDownload(test.type, test.date)}
                    className="flex-1 py-2.5 bg-red-500 text-white rounded-xl active:bg-red-600 transition-colors flex items-center justify-center"
                  >
                    <Download className="w-4 h-4 mr-2" />
                    Download
                  </button>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div className="text-center py-16">
            <div className="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <FileText className="w-8 h-8 text-gray-400" />
            </div>
            <p className="text-gray-900 mb-1">No test history yet</p>
            <p className="text-gray-500 text-sm">Completed tests will appear here</p>
          </div>
        )}
 
        {/* Health Trends */}
        {testHistory.length > 0 && (
          <div className="mt-6 bg-white rounded-3xl p-6 shadow-sm">
            <h3 className="text-gray-900 mb-3">Health Trends</h3>
            <p className="text-xs text-gray-400 mb-4">Health trend data is illustrative. For clinical advice please consult a medical professional.</p>
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-gray-600">Resting Heart Rate</span>
                <span className="text-green-600">Stable ↔</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-gray-600">Test Frequency</span>
                <span className="text-blue-600">On Track ✓</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-gray-600">Overall Health</span>
                <span className="text-green-600">Excellent ★</span>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}